version: "3.5"

volumes:
  mongodb:
  media:
  front:
  admin:
  redis:

services:
  api:
    build: ./api
    container_name: ebiblo_api
    image: ebiblo_api
    volumes:
      - media:/app/public
    env_file:
      - .env
    environment:
      - "GOOGLE_APPLICATION_CREDENTIALS=/app/firebase.json"
    depends_on:
      - mongo
      - redis
    expose:
      - ${PORT}

  front:
    build: ./front
    container_name: ebiblo_front
    image: ebiblo_front
    volumes:
      - front:/app/build
    env_file:
      - .env
    environment:
      - PUBLIC_URL=

  admin:
    build: ./admin
    container_name: ebiblo_admin
    image: ebiblo_admin
    volumes:
      - admin:/app/build
    env_file:
      - .env

  mongo:
    container_name: ebiblo_mongo
    image: mongo:4.0
    volumes:
      - mongodb:/data/db
    ports:
      - "${MONGO_PUBLIC_PORT:-15724}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

  nginx:
    container_name: ebiblo_nginx
    build: ./nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - media:/usr/share/nginx/api
      - front:/usr/share/nginx/front
      - admin:/usr/share/nginx/admin
    environment:
      - NGINX_PORT
      - PUBLIC_HOST_ADDRESS
      - ADMIN_HOST_ADDRESS
    depends_on:
      - api

  redis:
    container_name: ebiblo_redis
    image: redis:alpine
    volumes:
      - redis:/var/lib/redis
