version: "3.5"

volumes:
  mongodb:
  redis:

services:
  redis:
    container_name: ebiblo_redis
    image: redis:alpine
    volumes:
      - redis:/var/lib/redis
    ports:
      - ${REDIS_PORT}:6379

  mongo:
    container_name: ebiblo_mongo
    image: mongo:4.0
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
